Use new registerApp endpoint
hpx7/rtag pull request #415
Opened 2022-10-05 02:13 UTC by hpx7

2022-10-05 17:16 UTC, dsiddharth commented
@hpx7 when I run the code, it doesn't use the `APP_ID` env variable when connecting to the coordinator:
```
Connected to coordinator at coordinator.hathora.dev with appId 13e8cf44ea582c038798a7083e0cc8719abbe6a476d8c2855028bac60a44f8e8 and storeId 05847ead-de77-4086-826c-7e83ea94172e
```

Can you fix this to use `APP_ID` when initiating the connection? It's just a JSON object that can be easily augmented and the coordinator already knows how to handle it: https://github.com/hathora/monorepo/blob/main/coordinator/src/services/storeService.ts#L54

2022-10-05 17:17 UTC, hpx7 commented
Should be fixed already https://github.com/hathora/server-sdk-ts/commit/aaf3b337b106d1e250b2231db8b0ea3c4e45affb

2022-10-05 17:33 UTC, dsiddharth commented
Yep, you're right. Just had to clear my gitignored file and it works as expected now:
```
Connected to coordinator at coordinator.hathora.dev with appId app-b125da32-5db8-4659-b0cf-28679f643146 and storeId 7851ad16-1b6c-4190-8b6c-44df4ce0f32d
Starting frontend at /Users/sdhulipalla/code/hathora/examples/pong/client/prototype-ui

> start
> vite


  vite v2.9.9 dev server running at:

  > Local:    http://localhost:3000/
  > Network:  http://172.20.10.11:3000/

  ready in 209ms.
```

2022-10-05 17:39 UTC, dsiddharth commented on src/commands/build.ts
>      } else {
do this as a `return`

2022-10-05 17:42 UTC, dsiddharth requested changes

2022-10-05 17:42 UTC, dsiddharth commented on src/utils.ts
> +  const res = await axios.post<{ appId: string; appSecret: string }>("https://coordinator.hathora.dev/registerApp");
make this configurable

2022-10-05 17:42 UTC, dsiddharth commented on src/utils.ts
> +    outputFileSync(join(rootDir, ".env"), `APP_ID=${appConfig.appId}\nAPP_SECRET=${appConfig.appSecret}\n`);
parse this, check if file doesn't exist or APP_ID isn't present, generate a new one

2022-10-06 15:47 UTC, dsiddharth approved these changes

2022-10-06 21:43 UTC, merged